### PR TITLE
fixed the 'Releases' url

### PR DESCRIPTION
**Pull request by miziel**

### CODE REVIEW

**Comment by miziel** [comment]
if merged, issue #411 can be closed

**Comment by fireice-uk** [comment]
It will be changed when we roll an update this weekend. That's why we ask people to open against the dev branch :)

**Comment by psychocrypt** [comment]
Please always provide pull requests again the dev branch: https://github.com/fireice-uk/xmr-stak/blob/master/CONTRIBUTING.md

**Comment by miziel** [comment]
ah, ok... sorry, didn't rtfm :(

**Pull request closed without merging**
