### PR TITLE
AMD compile instructions for macOS

### PR DESCRIPTION
**Pull request by hohl**
I'm using an AMD powered MacBook Pro and saw the note about missing info in the HowTo. That's what worked for me. I basically just turned on OpenCL support and disabled the CUDA support.

### CODE REVIEW

**Comment by psychocrypt** [comment]
THX for this pull request.
Could you please add a description how you installed the amd app sdk. I can not see any AMD specific things in you current added documentation.

**Comment by hohl** [comment]
There isn't any AMD native SDK (at least it doesn't seem like there is anyone supported by xmr-stak), it just uses OpenCL as described on the [AMD Build Options](https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile.md#amd-build-options). OpenCL comes pre-bundled with Xcode so no need to install anything. Everything compiled fine and when launching the binary it tells me that the AMD GPU has been detected and I'm getting some (extra) hash/s for the GPU:

```
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   47.4 |   45.5 |   31.4 |  1 |   47.0 |   45.4 |   31.4 |
|  2 |   47.1 |   45.4 |   31.4 |
-----------------------------------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m |
|  0 |   34.1 |   32.0 |   32.3 |
---------------------------
Totals:    175.6  168.3  126.4 H/s
Highest:   255.5 H/s
```

**Comment by psychocrypt** [comment]
Could you please add a sentense to the compile instructions that all amd
stuf is shiped with xcode. It is a very importent note.

**Comment by hohl** [comment]
Sure.

**Review by psychocrypt — APPROVED** [review]

**Comment by psychocrypt** [comment]
Could you please rebase this PR against the latest dev branch. I can not merge this PR before all conflicts are solved.

**Comment by hohl** [comment]
Sure. Done, rebased on the latest dev branch.

**Comment by zeitos** [comment]
hi @hohl  which gcc version did you use? I can't compile with your instructions
it's using clang

**Comment by hohl** [comment]
> hi @hohl which gcc version did you use?

Sorry, as this was written over 3 years ago, I can‘t tell you anymore.

**Pull request merged**
