### PR TITLE
Fix CN_MASK

### PR DESCRIPTION
**Pull request by catalanscoin**
Please make sure your PR is against **dev** branch. Merging PRs directly into master branch would interfere with our workflow.

### CODE REVIEW

**Comment by psychocrypt** [comment]
why do you think that the current implementation is wrong.

**Comment by fireice-uk** [comment]
@psychocrypt Both ways are exactly the same, read it as:

1. Subtract 1 to get all 1's
2. Shift right by 4 bits
3. Shift left by 4 bits

Whereas the new version is 

1. Shift right by 4 bits
2. Subtract 1 to get all 1's
3. Shift left by 4 bits

I prefer the first version since it is more organised logically.

**Comment by psychocrypt** [comment]
@fireice-uk  You are right. thanks , that is what I missed^^

**Comment by psychocrypt** [comment]
@catalanscoin Thanks for the PR but we will stay with the current implementation.

**Comment by catalanscoin** [comment]
It is not the same.

"CN_MASK = ((CN_MEMORY - 1) / 16) * 16;" === "CN_MASK = CN_MEMORY - 1;"

The correct operation is this one: constexpr uint32_t CN_MASK = (CN_MEMORY / 16 - 1) * 16;

I think this const is not used anywhere, but I would fix It.

**Pull request closed without merging**
