### PR TITLE
Updated compile instructions due to AMD APP SDK no longer available on AMD website

### PR DESCRIPTION
**Pull request by cialu**
Please make sure your PR is against **dev** branch. Merging PRs directly into master branch would interfere with our workflow.

### CODE REVIEW

**Comment by Spudz76** [comment]
Downvote since that's my webspace and it's not permanent

**Comment by cialu** [comment]
@Spudz76 the commit shows only the link to GitHub issue. In the meantime, we can study a different solution and then put it in the issue. Maybe, a public cloud.

What do you think about?

**Comment by Spudz76** [comment]
Assume AMD would eventually put it back up / their web is always like this

**Comment by cialu** [comment]
It's a temporary server problem, I have updated the issue.

**Pull request closed without merging**
