### PR TITLE
WIP: AMD: compile source code in parallel

### PR DESCRIPTION
**Pull request by psychocrypt**
Open a thread for eeach device to compile the OpenCL source code in parallel.
This decrease the start up time for multi GPU systems.

should solve (reduce) #1018

- [ ] please do not merge maybe I will implement a compiler cash

### CODE REVIEW

**Comment by jam3972** [comment]
With this PR it definitely starts each thread at the same time, but it doesn't seem to actually use multiple CPU threads in parallel to compile, so ends up with very similar total compile time.
Here is my 2xVegaFE (running 2 threads each) output comparison.

Before PR: 55 sec total
```
[2018-02-27 14:41:30] : Compiling code and initializing GPUs. This will take a while...
[2018-02-27 14:41:30] : Device 0 work size 8 / 32.
[2018-02-27 14:41:44] : Device 0 work size 8 / 32.
[2018-02-27 14:41:57] : Device 1 work size 8 / 32.
[2018-02-27 14:42:11] : Device 1 work size 8 / 32.
[2018-02-27 14:42:25] : Starting AMD GPU thread 0, no affinity.
[2018-02-27 14:42:25] : Starting AMD GPU thread 1, no affinity.
[2018-02-27 14:42:25] : Starting AMD GPU thread 2, no affinity.
[2018-02-27 14:42:25] : Starting AMD GPU thread 3, no affinity.
```
After PR, 51 seconds total:
```
[2018-02-27 14:45:00] : Compiling code and initializing GPUs. This will take a while...
[2018-02-27 14:45:01] : Device 0 work size 8 / 32.
[2018-02-27 14:45:01] : Device 0 work size 8 / 32.
[2018-02-27 14:45:01] : Device 1 work size 8 / 32.
[2018-02-27 14:45:01] : Device 1 work size 8 / 32.
[2018-02-27 14:45:51] : Starting AMD GPU thread 0, no affinity.
[2018-02-27 14:45:51] : Starting AMD GPU thread 1, no affinity.
[2018-02-27 14:45:51] : Starting AMD GPU thread 2, no affinity.
[2018-02-27 14:45:51] : Starting AMD GPU thread 3, no affinity.
```

With both methods my 4 thread i3-4150 CPU sits at 25% utilization (full on single thread) from xmr-stak.

Technically an improvement, but hoping there is a way to utilize full CPU to make that faster.

**Comment by psychocrypt** [comment]
Maybe we should akip this PR and implement a compiler cash. Please do not merge this PR because the parallel compile make a compile hash more complex.

**Comment by Norfolc** [comment]
It seems that there is some lock inside amdocl64.dll that prevents to run all threads in parallel.
As a result it reduces compilation time from 2:45 minutes to 2:30 for 6 Vega 56
I have AMD blockchain drivers.

**Comment by psychocrypt** [comment]
I am working on a prototype to add a compiler cache. I hope that I am
tomorrow ready to create the pr.

**Comment by psychocrypt** [comment]
OpenCL compiler cache is now available #1131

**Comment by psychocrypt** [comment]
I close this PR because the new compile cache in #1131 will speedup the startup much more than this PR.

**Pull request closed without merging**
