### PR TITLE
Add support for Talleo's mining algorithm.

### PR DESCRIPTION
**Pull request by mtl1979**
Talleo is rebranded Bittorium, which uses similar algorithm as TurtleCoin but without the "Lite" mask. No generic algorithm works with Talleo.

### CODE REVIEW

**Comment by psychocrypt** [comment]
do you tested the changes with all three platforms cpu/amd/nvidia?

**Comment by mtl1979** [comment]
I tested with cpu and nvidia... Don't have amd card.

**Comment by psychocrypt** [comment]
can you please post a real pool and a corresponding wallet address

**Comment by psychocrypt** [comment]
I need the pool also to check for the hashrate. we normally not accept
coins under 5mh/s (exceptions are sometimes possible)

**Comment by mtl1979** [comment]
With 60 second target time, the hash rate won't climb very high... I made temporary build so our miners can use GPUs to mine, otherwise the network hash rate doesn't start climbing.

I used pool.talleo.org:3334 to verify my patch is correct.

My own wallet address is:

TA4yACzMYuFYq7V6xVAWYHeS39jQ8w4mKRowpY6NskGuS1rZpjcWuCpdeCypwUCJrK9mGqVW9o1pY2EG3HW7BZkR2YRcc4YNa

**Comment by leisegang** [comment]
5mhs is now at the official pool. Can you please add talleo to xmr stak? 
https://leisegang.no/src/viphGPz7.png screenshot of hashrate

Pool port has changed to 3333
@psychocrypt

**Comment by mtl1979** [comment]
On some AMD GPUs, the auto configuration seems to set the intensity to double of usable value. I'm not really experienced at fixing that part of the code...

**Comment by psychocrypt** [comment]
the hashrate is very small let me discuss this with @fireice_uk. This will
take some time because we are busy with other development

**Comment by mtl1979** [comment]
@psychocrypt We lost some miners because of a bug in mining pool software... We already fixed the bug on two pools and will fix it on the third too. It takes more time on the third pool because it is running nodejs-pool and not software designed specifically for Talleo.

**Pull request closed without merging**
