### PR TITLE
Add compilation instructions for MacOS

### PR DESCRIPTION
**Pull request by michaelbaudino**
This PR is a repost of #169 with some modifications to address @psychocrypt review.

It adds compilation instructions (including dependencies installation instructions) for MacOS for either Nvidia GPUs or CPU-only mining.

### CODE REVIEW

**Comment by ExceptionallyGreat** [comment]
Suggestion: Add the installation command for Homebrew, instead of provide text that assumes it is already installed.

**Comment by yachi** [comment]
for AMD, just install XCode then ok, no need app sdk

**Comment by yachi** [comment]
cmake:

```
cmake . -DOpenCL_ENABLE=ON -DCUDA_ENABLE=OFF -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
```

**Comment by kth5** [comment]
Actually CUDA works fine on Sierra using a Quadro K620. GUI becomes mostly unusable but it does seem to work fine.

Downloaded CUDA SDK 9.0 and matching driver and CLT for Xcode 9.0.

```
cmake . -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCUDA_ARCH="35;60"
```

**Comment by michaelbaudino** [comment]
Thanks for merging 🎉 

@yachi Thanks for your AMD-related feedback. This PR was merged already, but would you mind creating another one with compilation instructions (I can't test it myself, so you're probably in better position than me to write it 😊)

**Pull request merged**
