### PR TITLE
remove cryptonight coins

### PR DESCRIPTION
**Pull request by psychocrypt**
- remove all cryptonight coins (algorithm cryptonight can still be used)
- update README.md

### CODE REVIEW

**Comment by fireice-uk** [comment]
I would opt to remove them altogether - we have pretty much zero cn-original donations, what's the point of maintaining unused coins?

**Comment by Spudz76** [comment]
If more coins besides Electroneum switch back to the cn-original version due to [CG]PU miners doing too much profit switching and leaving the network slow on transaction processing, then it is still potentially valuable in the future, not necessarily deprecated.

**Comment by psychocrypt** [comment]
I removed all native cryptonight coins

**Comment by fireice-uk** [comment]
@Spudz76 We are not removing the algo, that remains, we are removing the named coin support for those coins.

**Pull request merged**
