### PR TITLE
Add cryptonight_electronero and cryptonight_pulse

### PR DESCRIPTION
**Pull request by shopglobal**
These two algos cryptonight_electronero (ETNX) and cryptonight_pulse (ETNXP) are based on cryptonight_masari aka cryptonight_fast mining algorithm. Meaning the iterations are adjusted and these algorithms are built on top of cryptonight fundamentals. The main reason for the PR is that they will maintain their own space. Since future algo changes must remain coin specific. As per recent news from Dr.Margus Borkenstein who retorted that "most unique algorithm signatures in the cryptocurrency space will receive significant exposure to be documented in the near future". Our own research is still being concluded and future algorithm updates will be coin specific.

Here's some pools on the list for verification:

cryptonight_electronero -- Electronero (ETNX): https://pool.electronero.org
pool.electronero.org

cryptonight_pulse -- Electronero Pulse (ETNXP): https://pool.electroneropulse.org
pool.electroneropulse.org

Check also the mining pool stats stream: 
Electronero
https://miningpoolstats.stream/electronero
Electronero Pulse
https://miningpoolstats.stream/electronero-pulse

### CODE REVIEW

**Comment by shopglobal** [comment]
Here's our logo (hover to see the title text):

Inline-style: 
alt text
https://ibb.co/vdcymZF
https://ibb.co/ynfmzFM

**Comment by c1pzo** [comment]
💪

**Comment by fireice-uk** [comment]
Hi! I don't like to clutter commit history. Please squash your commits so that you have one per algo.

**Comment by shopglobal** [comment]
@fireice-uk May I suggest you enable squash and merge in Settings panel? Since I don't have write access yet to repo I cannot. Squash and merge is on the repo settings panel enable settings >> Allow squash commits. 

![github.com]https://i.ibb.co/jDPnxpw/Fire-Shot-Capture-298-Options-https-github-com-Altcoin-Coop-xmr-stak-settings.png "")

would that suffice for this PR #2098

**Comment by shopglobal** [comment]
> These two algos cryptonight_electronero (ETNX) and cryptonight_pulse (ETNXP) are based on cryptonight_masari aka cryptonight_fast mining algorithm. Meaning the iterations are adjusted and these algorithms are built on top of cryptonight fundamentals. The main reason for the PR is that they will maintain their own space. Since future algo changes must remain coin specific. As per recent news from Dr.Margus Borkenstein who retorted that "most unique algorithm signatures in the cryptocurrency space will receive significant exposure to be documented in the near future". Our own research is still being concluded and future algorithm updates will be coin specific.
> 
> Here's some pools on the list for verification:
> 
> cryptonight_electronero -- Electronero (ETNX): https://pool.electronero.org
> pool.electronero.org
> 
> cryptonight_pulse -- Electronero Pulse (ETNXP): https://pool.electroneropulse.org
> pool.electroneropulse.org
> 
> Check also the mining pool stats stream:
> Electronero
> https://miningpoolstats.stream/electronero
> Electronero Pulse
> https://miningpoolstats.stream/electronero-pulse

New clean 1 commit branch #2099:
https://github.com/fireice-uk/xmr-stak/pull/2099

**Pull request closed without merging**
