### PR TITLE
Add optional ROCm early-opencl-init

### LINKED ISSUE #1693: xmr-stak and AMD's ROCm OpenCL ICD do not correctly enumerate when called from a plugin context, but not if openCL is enumerated early.
So while attempting to get xmr-stak working on my RX Vega 64 system, I discovered that when using the ROCm 1.8.x OpenCL, darktable and clinfo work fine, but xmr-stak fails to enumerate any devices.  I am not sure how, but I think some dlopen/dlsym or thread setup hijinkery is conflicting with ROCm's libamdocl64.so initialization.

I have been able to produce a working xmr-stak by adding an 'early' clGetPlatformIDs call to executor::ex_main before miner_work or any plugins are initialized.  I have this (small) patch available at https://github.com/fireice-uk/xmr-stak/compare/dev...kainz:early_rocm_init.

What I am uncertain of is if this is a bug in the ROCm OpenCL runtime, or in ocl-icd, or in xmr-stak's setup process.  If implementing this as a workaround is possible, I would propose merging this patch in, and making a note of it in COMPILING.md and the setup/install documentation for people that start using newer AMD drivers.

Please provide as much as possible information to reproduce the issue.

# Basic information
  - CPU: Core i7-5820K
  - GPU: RX Vega 64 8GB

# Compile issues
  - Ubuntu 16.04.4 w/ ROCm 1.8.1
  ```
  cmake -DCMAKE_LINK_STATIC=on -DXMR-STAK_COMPILE=generic -DCMAKE_LINK_STATIC=ON -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=ON
  ```
  ```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kain/external-code/xmr-stak/build
-- Cache values
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_PREFIX:PATH=/home/kain/external-code/xmr-stak/build
CMAKE_LINK_STATIC:BOOL=ON
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=ON
CUDA_ENABLE:BOOL=OFF
EXECUTABLE_OUTPUT_PATH:STRING=bin
HWLOC:FILEPATH=/usr/lib/x86_64-linux-gnu/libhwloc.so
HWLOC_ENABLE:BOOL=ON
HWLOC_INCLUDE_DIR:PATH=/usr/include
LIBRARY_OUTPUT_PATH:STRING=bin
MHTD:FILEPATH=/usr/lib/x86_64-linux-gnu/libmicrohttpd.so
MICROHTTPD_ENABLE:BOOL=ON
MTHD_INCLUDE_DIR:PATH=/usr/include
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcrypto.so
OPENSSL_INCLUDE_DIR:PATH=/usr/include
OPENSSL_SSL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libssl.so
OpenCL_ENABLE:BOOL=ON
OpenCL_INCLUDE_DIR:PATH=/usr/include
OpenCL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libOpenCL.so
OpenSSL_ENABLE:BOOL=ON
PKG_CONFIG_EXECUTABLE:FILEPATH=/usr/bin/pkg-config
XMR-STAK_COMPILE:STRING=generic
  ```

# Issue with the execution
  - Yes, I am using a self-compiled xmr-stak.
  ```
Version: xmr-stak/2.4.5/b3f79de/master/lin/amd-cpu/aeon-cryptonight-monero/0
  ```

# AMD OpenCl issue

  ```
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.1 AMD-APP.internal (2617.0)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_object_metadata cl_amd_event_callback 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     gfx900
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 
  Driver Version                                  2617.0 (HSA1.1,LC)
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Board Name (AMD)                         Device 687f
  Device Topology (AMD)                           PCI-E, 03:00.0
  Max compute units                               64
  SIMD per compute unit (AMD)                     4
  SIMD width (AMD)                                16
  SIMD instruction width (AMD)                    1
  Max clock frequency                             1630MHz
  Graphics IP (AMD)                               9.0
  Device Partition                                (core)
    Max number of sub-devices                     64
    Supported partition types                     none specified
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             256
  Preferred work group size multiple              64
  Wavefront width (AMD)                           64
  Preferred / native vector sizes                 
    char                                                 4 / 4       
    short                                                2 / 2       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 1 / 1        (cl_khr_fp16)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     No
    Infinity and NANs                             No
    Round to nearest                              No
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              8573157376 (7.984GiB)
  Global free memory (AMD)                        8370176 (7.982GiB)
  Global memory channels (AMD)                    64
  Global memory banks per channel (AMD)           4
  Global memory bank width (AMD)                  256 bytes
  Error Correction support                        No
  Max memory allocation                           7287183769 (6.787GiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        16384
  Global Memory cache line                        64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             26751
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               65536 (64KiB)
  Local memory syze per CU (AMD)                  65536 (64KiB)
  Local memory banks (AMD)                        32
  Max constant buffer size                        7287183769 (6.787GiB)
  Max number of constant args                     8
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Profiling timer offset since Epoch (AMD)        0ns (Wed Dec 31 16:00:00 1969)
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Thread trace supported (AMD)                  No
  printf() buffer size                            4194304 (4MiB)
  Built-in kernels                                
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_media_ops cl_amd_media_ops2 cl_khr_subgroups cl_khr_depth_images cl_amd_copy_buffer_p2p cl_amd_assembly_program 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  AMD Accelerated Parallel Processing
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [AMD]
  clCreateContext(NULL, ...) [default]            Success [AMD]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   gfx900
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   gfx900

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.12
  ICD loader Profile                              OpenCL 2.2
	NOTE:	your OpenCL library declares to support OpenCL 2.2,
		but it seems to support up to OpenCL 2.1 only.

  ```

# Stability issue
  - Is the CPU or GPU overclocked? No
  - Is the Main memory of the CPU or GPU undervolted? No

### PR DESCRIPTION
**Pull request by kainz**
- Fix execution on ROCm platform by optionally calling an opencl
   list-platforms before any thread or dlopen/sym hijinkery can happen.

Fixes #1693.

### CODE REVIEW

**Comment by psychocrypt** [comment]
Thx for the PR. Why do we need this init call before dlopen? The problem
with this fix is that xmr-stak is designed that it is compiled with opencl
support but the execution system do not need it. With this fix the xmr-stak
binary must be linked against opencl which than requires opencl.
Could you please explain why I am not allowed to call dlopen before.
That no other thread is spawned before can be avoided but from the design
opencl must be linked only against the xmr-stakamdbackend.dll/so file to
avoid that we enforce opencl.

**Comment by psychocrypt** [comment]
Could you please try to add this early init to `backend/amd/minethd.cpp` to
the function xmrstak_start_backend as first call. This is still in the
mainthread process and has hopefully the same effect. If this works the
issue with the forced opencl dependency would be solved.

**Comment by kainz** [comment]
Sure, I'll try some more shuffling around, but I'm not sure it worked before.

**Comment by psychocrypt** [comment]
Let me resume what you suggest to be sure we talk about the same things.
A possible patch is to add two flags to the dlopen api. Is this correct?
Does this avoid that xmr-stak is linked against opencl. Could you write a
patch with the workaround without an option in the cfg files that I can see
what is currently a possible fix.

**Comment by psychocrypt** [comment]
I think now I understand it. Please create a patch wherr you call the
dlopen only if rocm is used directly before the amd backend is loaded. Do
not use the hardcoded path only call the library. The user must have set
his LD_LiBRARY_PATH correct. please handle the error if the lib is not
found, throw a warning message and try to load the amd backend even if the
emulated preload is not working.

**Comment by kainz** [comment]
So what I'm suggesting and have observed on further investigation is that when libOpenCL is loaded by the automatic linkage to the plugin shared library, something breaks on ocl-icd-loader's dlopening() of the OpenCL platform or maybe on attempting calls into the OpenCL API. Using either a LD_PRELOAD, or inserting a dlopen() call to pre-open the platform driver before calling into the plugin works.

Doing that dlopen() does avoid linking xmr-stak against OpenCL -- so it's not changing flags to the plugin's dl call, its calling a second dlopen before the plugin itself, to ensure that the platform driver can load without any conflicts that in my theory are triggered by something linked in/with the libxmrstak_opencl_backend.so.

So essentially yeah, pretty much just what you mentioned. I'll bang that out.

**Comment by kainz** [comment]
So it turns out I'm having to RMA my test card.  I'll try to get to this still, but I won't be able to validate it.  Was anyone else out there running xmr-stak opencl on ROCm 1.8?

**Comment by psychocrypt** [comment]
I need to check the issues we have a few reports

Bryon Roché <notifications@github.com> schrieb am So., 8. Juli 2018, 23:55:

**Comment by kainz** [comment]
The hallmark will be anyone saying the opencl miner fails but comes with a clinfo that has platforms and says `amd accelerated parallel processing` like in my issue #1693. Maybe newer amdgpu-pro users see similar but I'm not sure what that ICD reports.

**Comment by psychocrypt** [comment]
I am not sure if this workaround is really needed, I tested the code today on a system with rocm installed. I build against the rocm shipped  OpenCl (used as host compiler gcc) and all works fine.

**Comment by kainz** [comment]
We're you using the packaged and driver rocm or the open source rocm? They are quite similar but there are some differences between the two, I believe? Also, what distro are you using? Ubuntu 18.04? 16?

**Comment by psychocrypt** [comment]
How can I figure out which rocm is installed. I get only access to a system
but have not installed it.

**Comment by kainz** [comment]
Good question. `dpkg -l | grep rocm`, use `dpkg -s whateveristherocm-openclpackage` too see the info & version?

On July 19, 2018 3:01:25 PM CDT, psychocrypt <notifications@github.com> wrote:
>How can I figure out which rocm is installed. I get only access to a
>system
>but have not installed it.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/fireice-uk/xmr-stak/pull/1694#issuecomment-406396638

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by psychocrypt** [comment]
dpkg is not available it is a centos. I tried hcc -v and got `HCC clang
version 7.0.0` But this shows only that it must be some newer rocm stack
but nothing about the driver.

**Comment by psychocrypt** [comment]
dpkg is not available it is a centos. I tried hcc -v and got 

```
HCC clang version 7.0.0 (ssh://gerritgit/compute/ec/hcc-tot/clang 86791fc4961dc8ffde77bde20d7dfa5e5cbeff5e)
```

But this shows only that it must be some newer rocm stack
but nothing about the driver.

**Comment by kainz** [comment]
Clinfo?

**Comment by psychocrypt** [comment]
yes that is a good idea: `Driver version:				 2617.0 (HSA1.1,LC)`

**Comment by psychocrypt** [comment]
AhhbI forget that I onle tested if it is running. What I missed is to check
if the shares are valid. In my case they are invalid this means it runs
with rocm but there must be something compiled wrong.

**Comment by kainz** [comment]
So trying a fresh set of builds on ubuntu 18.04, linux 4.18-rc6, fresh (git-master) rocm-opencl-runtime, roct-thunk-interface (fxkamnd/drm-next-wip branch), and rocr-runtime 1.8.1, I am able to produce a working dev-branch xmr-stak without needing to do any preloading fuckery.

I do need to disable the NVidia opencl icd in the ocd driver loader when I do this, but I chalk that up to a bug somewhere in the amd opencl icd actually.

For the amd system you were testing, getting a new enough (idk if rocm 1.8.2 is new enough) rocm-opencl-runtime will fix the miscompile errors, I've tested that on xmrig-amd and xmr-stak.  I'll withdraw this PR and my bug.

Cheers.

**Pull request closed without merging**
