### PR TITLE
add cryptonight_v8_double

### PR DESCRIPTION
**Pull request by psychocrypt**
close: https://github.com/fireice-uk/xmr-stak/issues/2263

Add new algorithm alias for cryptonight_v8_double. The difference to v8
is that the number of iterations is increased.

Add also the currency X-CASH which use cryptonight_double.

### CODE REVIEW

**Comment by AnimusXCASH** [comment]
Hi,
mining pool
http://minexcash.com/#getting_started

The difference from our algo to regular CN V8 is we have double the iterations than CN V8. the scratchpad is still 2MB

Where do you want that I send you wallet?

**Comment by psychocrypt** [comment]
Thx I already found the online wallet generator. I needed only a address
for the short tests against a pool. Since the pow only changed the number
of iterations it was easy to integrate it.

**Comment by AnimusXCASH** [comment]
> Thx I already found the online wallet generator. I needed only a address
> for the short tests against a pool. Since the pow only changed the number
> of iterations it was easy to integrate it.

great, could you give as an EST. time when it will be integrated? 

thanks

**Comment by psychocrypt** [comment]
my personal schedule is to release in the next 24h.

**Pull request merged**
