### PR TITLE
Update compile process (Windows)

### PR DESCRIPTION
**Pull request by 7022Andre**
Added/Rewrote/Clarified instructions on how to compile in Windows; Fixed some typos and syntax; Added build option section.

### CODE REVIEW

**Comment by globsch** [comment]
this schould be added.
espacially: 

> https://github.com/fireice-uk/xmr-stak/pull/969/commits/c7d136fe308cfb39c8fe05c6ee615f579238b2ab#diff-675aa9e62255016d282f728306a4748fR16

**Comment by fireice-uk** [comment]
@7022Andre Can you please rebase your pr?

**Comment by 7022Andre** [comment]
@fireice-uk I fixed the merge conflict.

**Comment by 7022Andre** [comment]
@fireice-uk Anything else you'd like me to add or fix?

**Comment by fireice-uk** [comment]
@7022Andre Look ok! Thanks!

**Pull request merged**
