### PR TITLE
[WIP] unify local memory

### PR DESCRIPTION
**Pull request by psychocrypt**
This pull request should increase the speed to cache the AES table into the local memory

- unify local memory to flat one dimensional array with 1024 entries
- extent AES table to 1024 entries

# Help Wanted

Please compare the speed of the current dev with this pull request

maybe @JerichoJones @davidpesce @anhphan

### CODE REVIEW

**Comment by fsck0ff** [comment]
Ok so here are my tests, on PR624 and PR637:
[vegapr.txt](https://github.com/fireice-uk/xmr-stak/files/1577191/vegapr.txt)
In short PR624 crashes my Vega56 while it seems to be working very well with my R9 Nano and PR637 seems to be working fine with Vega56 (Intensity 3144 gives about 1100hps) which is about the same I am getting with 2.1.0. All tests were run under ubuntu 16.04 with amdgpu 17.50 under docker (which may or may not have any effect on the tests...).

**Comment by Njeroe** [comment]
Hi, on 2x Vega 64 with the autoconfig 1536 intensity i get this
`[2017-12-21 00:34:30] : WARNING: backend NVIDIA disabled.
[2017-12-21 00:34:30] : Found AMD platform index id = 0, name = Advanced Micro Devices, Inc.
[2017-12-21 00:34:30] : Found OpenCL GPU .
[2017-12-21 00:34:30] : Found OpenCL GPU .
[2017-12-21 00:34:30] : AMD: GPU configuration stored in file 'amd.txt'
[2017-12-21 00:34:30] : Compiling code and initializing GPUs. This will take a while...
[2017-12-21 00:34:30] : Device 0 work size 8 / 32.
[2017-12-21 00:34:36] : Device 1 work size 8 / 32.
[2017-12-21 00:34:43] : Starting AMD GPU thread 0, no affinity.
[2017-12-21 00:34:43] : Starting AMD GPU thread 1, no affinity.
[2017-12-21 00:34:43] : Fast-connecting to pool.supportxmr.com:7777 pool ...
[2017-12-21 00:34:43] : Pool pool.supportxmr.com:7777 connected. Logging in...
[2017-12-21 00:34:43] : Difficulty changed. Now: 25000.
[2017-12-21 00:34:43] : Pool logged in.
[2017-12-21 00:34:51] : Result accepted by the pool.
[2017-12-21 00:34:54] : Result accepted by the pool.
[2017-12-21 00:34:56] : Difficulty changed. Now: 115381.
[2017-12-21 00:34:56] : New block detected.
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 | 1310.3 |   (na) |   (na) |  1 | 1318.6 |   (na) |   (na) |
-----------------------------------------------------
Totals:   2628.9   (na)   (na) H/s
Highest:  2611.2 H/s
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 | 1315.7 |   (na) |   (na) |  1 | 1324.7 |   (na) |   (na) |
-----------------------------------------------------
Totals:   2640.4   (na)   (na) H/s
Highest:  2636.4 H/s
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 | 1308.8 |   (na) |   (na) |  1 | 1326.0 |   (na) |   (na) |
-----------------------------------------------------
Totals:   2634.8   (na)   (na) H/s
Highest:  2639.2`

on 2016 intensity i get this
`2017-12-21 00:38:47] : WARNING: backend NVIDIA disabled.
[2017-12-21 00:38:47] : Compiling code and initializing GPUs. This will take a while...
[2017-12-21 00:38:47] : Device 0 work size 8 / 32.
[2017-12-21 00:38:54] : Device 1 work size 8 / 32.
[2017-12-21 00:39:00] : Starting AMD GPU thread 0, no affinity.
[2017-12-21 00:39:00] : Starting AMD GPU thread 1, no affinity.
[2017-12-21 00:39:00] : Fast-connecting to pool.supportxmr.com:7777 pool ...
[2017-12-21 00:39:00] : Pool pool.supportxmr.com:7777 connected. Logging in...
[2017-12-21 00:39:01] : Difficulty changed. Now: 25000.
[2017-12-21 00:39:01] : Pool logged in.
[2017-12-21 00:39:04] : Difficulty changed. Now: 45455.
[2017-12-21 00:39:04] : New block detected.
[2017-12-21 00:39:05] : Result accepted by the pool.
[2017-12-21 00:39:08] : Result accepted by the pool.
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 | 1558.1 |   (na) |   (na) |  1 | 1571.5 |   (na) |   (na) |
-----------------------------------------------------
Totals:   3129.6   (na)   (na) H/s
Highest:  3124.6 H/s`

anything above 2016 ends up like this
`[2017-12-21 00:40:33] : WARNING: backend NVIDIA disabled.
[2017-12-21 00:40:33] : Compiling code and initializing GPUs. This will take a while...
[2017-12-21 00:40:33] : Device 0 work size 8 / 32.
[2017-12-21 00:40:34] : Error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer to create hash scratchpads buffer.
[2017-12-21 00:40:34] : WARNING: AMD device not found
[2017-12-21 00:40:34] : WARNING: backend AMD disabled.
[2017-12-21 00:40:34] : ERROR: No miner backend enabled.
Press any key to exit.[2017-12-21 00:41:17] : WARNING: backend NVIDIA disabled.
[2017-12-21 00:41:17] : Compiling code and initializing GPUs. This will take a while...
[2017-12-21 00:41:17] : Device 0 work size 8 / 32.
[2017-12-21 00:41:17] : Error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer to create hash scratchpads buffer.
[2017-12-21 00:41:17] : WARNING: AMD device not found
[2017-12-21 00:41:17] : WARNING: backend AMD disabled.
[2017-12-21 00:41:17] : ERROR: No miner backend enabled.
Press any key to exit.`

on 2.1.0 I get 2030 h/s windows10 with aug23 blockchain driver...

**Comment by psychocrypt** [comment]
@Njeroe Thx for testing. This pull request you tested not support intensities over 2016 per miner thread. If you like to test higer intensities you must use #624

@fsck0ff Thx for your tests: I am a little bit confused by your results. You tested this PR which is a unified local memory patch with `intensity = 3144` without a crash. Such a high intensity should only be supported by #624.

**Comment by fsck0ff** [comment]
Well, I just tested it again, and with the source from `git clone https://github.com/psychocrypt/xmr-stak.git -b topic-unifyLocalMemory` built the maximum intensity I can get to is 3472. Above that vega56 crashes. I also verified that changes from #624 aren't present so I guess #637 does support such high intensity.

**Comment by bradmccormack** [comment]
Hi @psychocrypt  thanks for your work. Here are my test results.

Hardware
```
2 x Vega 56
4 GB ram
30GB Virtual 
```

OS
```
Windows 10 Pro
Version 1709
OS Build 16299.125
```

Driver
`aug23 blockchain driver`


Hardware settings 
```
[Profile_0]
Name=Vegas-Stable
GPU_P0=852;900
GPU_P1=991;900
GPU_P2=1084;900
GPU_P3=1138;900
GPU_P4=1150;900
GPU_P5=1202;900
GPU_P6=1212;905
GPU_P7=1407;950
Mem_P0=167;900
Mem_P1=500;900
Mem_P2=800;900
Mem_P3=950;900
Fan_Min=3000
Fan_Max=4900
Fan_Target=75
Fan_Acoustic=2400
Power_Temp=85
Power_Target=0
```

XMR-Stak AMD settings
```
"gpu_threads_conf" : [
{ "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1 },
{ "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1 },
{ "index" : 1, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1 },
{ "index" : 1, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1 },
],
```

Existing XMR-Stak
`Version xmr-stak 2.0.0 0005e4a`

Existing average hashrate 15 min- 3875.3
Notes - CPU mining disabled.

Your Build
`xmr-stak 2.1.0 2a81c70`

Average hashrate - Fail
Notes - 

CPU mining disabled.
The miner app started then failed and eventually the computer became unresponsive. I'll have a look into the Event log later.  No hardware changes etc.

**Comment by psychocrypt** [comment]
Thanks for your feedback. It looks like I need to fix it next year as soon
as I have new amd equipment.

**Comment by psychocrypt** [comment]
@JerichoJones  and all other follower coul you please this pull request with a VEGA GPU.
Please report the hash rate with the current release or dev and this PR.

I fixed a small bug but some of you reported that the miner crashed on VEGA therefore we need to check it again.

**Comment by JerichoJones** [comment]
AMD RADEON RX 64
Best settings
Ver | Intensity | 60 sec hashrate
xmr-stak/2.2.0/86db16f3/unknown/win/nvidia-amd-cpu/aeon-monero/20 | 1636/1636 | 2033
xmr-stak/2.2.0/dded06a3/unknown/win/nvidia-amd-cpu/aeon-monero/20 | 1932/1932 | 2187

**Comment by psychocrypt** [comment]
@JerichoJones I am correct that you get lesser hash rates with this PR?

**Comment by JerichoJones** [comment]
yes

**Comment by psychocrypt** [comment]
Thank you for all the test, I will close this PR because there is no benefit visible.

**Pull request closed without merging**
