### PR TITLE
Update compile_Windows.md

### PR DESCRIPTION
**Pull request by ExceptionallyGreat**
Updated dependencies and steps for build.

### CODE REVIEW

**Comment by psychocrypt** [comment]
Thanks for you first PR.
I will check the changes soon. I looked shortly over it and it could be that I will pick some of the changes but not all (if so I keep the author).

**Comment by ExceptionallyGreat** [comment]
You are welcome!
It is your call. I have tested the changes on my Windows Machine, and I can confirm they work. If you need me to make any changes, I can do that as well.

**Comment by ExceptionallyGreat** [comment]
I could use a little help here please. I committed one code change into my fork, and somehow it got automatically added to this pull request. How do I remove that?

**Comment by psychocrypt** [comment]
This is not a bug this is a feature.
This is that you have the possibility to change your current pull request.
You should create a new branch each time you working on a feature. Than
create out of the feature branch a pull request.
If you worked before with svn than keep in mind git is not svn. Open for
everything a new branch.

http://nvie.com/posts/a-successful-git-branching-model/

**Comment by psychocrypt** [comment]
You created this PR from your dev branch. This is not optimal. Best close
this issue and create a branch out auf the latest dev from us and than
create a new PR with your changes.

**Comment by ExceptionallyGreat** [comment]
Thank you for explaining, this is my first time using git/github. I will close this out and do as suggested.

**Pull request closed without merging**
