### PR TITLE
Spell check again, refreshed

### PR DESCRIPTION
**Pull request by Spudz76**
This should be correctly based on latest dev this time and a single commit.

### CODE REVIEW

**Comment by Spudz76** [comment]
Updated and squashed for latest dev commit, added typo fix in brand new code `alogo ->algo`

**Comment by fireice-uk** [comment]
Review url: https://github.com/fireice-uk/xmr-stak/pull/1465/files?w=1

Looks like you need to resolve the conflicts again, sorry =).

**Comment by Spudz76** [comment]
I wondered if Github had a squelch whitespace option, nice!

**Comment by fireice-uk** [comment]
@Spudz76 I cherry picked your commit to #1535 partly because Travis banned new contributors to our repo, and partly because I didn't want to ask you to fix merge problems again :P

**Comment by Spudz76** [comment]
Thanks!

**Pull request closed without merging**
