### PR TITLE
fix windows compile with CUDA 9.1

### LINKED ISSUE #523: MSB6006 on Cuda 9.1 xmr stak Windows Compile
Hi there,

I got following error when trying compile xmr stak (lastest git).
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" wurde mit dem Code 1 beendet. [C:\xmr\build\xmrstak_cuda_backend.vcxproj]`

# Basic information
  - Intel i7 - 5960X
  - NVidia 1080Ti

# Compile issues
  - Windows 10 Pro 1709

Here is the cmake output:

C:\xmr\build>cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
-- The C compiler identification is MSVC 19.12.25830.2
-- The CXX compiler identification is MSVC 19.12.25830.2
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1 (found suitable version "9.1", minimum required is "7.5")
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: C:/Program Files (x86)/AMD APP SDK/3.0/lib/x86_64/OpenCL.lib (found version "2.0")
-- Found OpenSSL: C:/xmr-stak-dep/openssl/lib/libeay32.lib (found version "1.0.2m")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/xmr/build

And this is also the the error in the end:
"C:\xmr\build\install.vcxproj" (Standardziel) (1) ->
"C:\xmr\build\ALL_BUILD.vcxproj" (Standardziel) (3) ->
"C:\xmr\build\xmrstak_cuda_backend.vcxproj" (Standardziel) (7) ->
(CustomBuild Ziel) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" wurde
mit dem Code 1 beendet. [C:\xmr\build\xmrstak_cuda_backend.vcxproj]

    40 Warnung(en)
    1 Fehler

### PR DESCRIPTION
**Pull request by psychocrypt**
fix compile on windows together with #532 
fix #523 and #534

apply cmake patch for CUDA 9.0 also for CUDA 9.1

### CODE REVIEW

**Comment by Makanar** [comment]
"apply cmake patch for CUDA 9.0 also for CUDA 9.1"

How do I do this? Google search for cmake CUDA patch is not helpful.

**Comment by Makanar** [comment]
How do I get all changes up until this point, #549? downloading a zip of https://github.com/fireice-uk/xmr-stak/tree/31c7598168debeaad26e91e36409a25808a8a6c4 does not give me previous changes such as #532 

Thanks, sorry if noob question

**Comment by DavidBruchmann** [comment]
https://stackoverflow.com/questions/14872486/retrieve-specific-commit-from-a-remote-git-repository

**Comment by DavidBruchmann** [comment]
If you don't have git installed: https://git-scm.com/downloads

**Pull request merged**
