### PR TITLE
Docs - compilation RAM requirements

### PR DESCRIPTION
**Pull request by maurezen**
Ran into `g++: internal compiler error: Killed (program cc1plus)` while compiling on low-RAM VPS, wasn't obvious that there wasn't enough RAM to compile.
Updating linux compile instructions and FAQ.

### CODE REVIEW

**Comment by psychocrypt** [comment]
could you please rebase your PR against the dev branch.

**Comment by maurezen** [comment]
@psychocrypt it is against the dev branch in the first place and there are no conflicts, what's the point?

**Comment by psychocrypt** [comment]
You pulled in merge pull requests from the master to the dev with this PR. Bu I will merge it as it is.

**Comment by maurezen** [comment]
@psychocrypt sorry, I was doing that from the web interface, I suppose that screwed something up

**Pull request merged**
