### PR TITLE
release 2.3.0

### PR DESCRIPTION
**Pull request by psychocrypt**
Config files from **2.2.0** are NOT compatible. Please use a new folder for the miner or remove all old config files.

# Changelog:

- AMD backend
  - add compiler cache (speedup startup time) #1131
  - add new - memory pattern (new tweak option) #1109
  - add Mesa OpenCl support #1101
  - reduce register usage #1080
  - fix AEON auto suggestion #1030
- NVIDIA back-end
  - increase Volta hashrate #1014
  - reduce startup time #1121
  - reduce memory foot print #950
- Other
  - support for Monero POW change #1200 
  - support for Sumokoin POW change #1200
  - add command line option `--benchmark BLOCKVERSION` #1200
  - native support for different cryptonight forks  #1200
  - support for pool owner to generate a pool config

### CODE REVIEW

**Comment by fireice-uk** [comment]
It's a boy!

**Comment by fireice-uk** [comment]
Wow. It's a boy!

**Comment by psychocrypt** [comment]
@stempelo you can test mine against [this](http://killallasics.moneroworld.com/) testnet pool. You must use the testnet address shown in the link.

**Comment by stempelo** [comment]
I don't understand why i have this...
[2018-03-25 23:44:26] : Result rejected by the pool.
[2018-03-25 23:44:26] : New block detected.

**Comment by psychocrypt** [comment]
to you use monero7?

**Comment by psychocrypt** [comment]
which hardware do you use? AMD,NVIDIA or CPU?

**Comment by stempelo** [comment]
CPU now, tomorrow i'll test with AMD RX 480

**Comment by stempelo** [comment]
Sorry, my mistake, I reported the changes incorrectly in the cryptonight_hash function.

Now I tried again on killallasics.moneroworld.com and:
[2018-03-27 22:16:03]: Result accepted by the pool.
[2018-03-27 22:16:04]: New block detected.

**Pull request merged**
