### PR TITLE
Add rig identifier

### PR DESCRIPTION
**Pull request by fireice-uk**
Tested on snipa's pool, minergate and nanopool.

- [x] Needs to be tested on nicehash.

### CODE REVIEW

**Comment by psychocrypt** [comment]
Is this a common tag or only supported by some pools? 
What should be tested with nicehash? I run it on the nicehash pool but worker names are only shown if the name is added to the address [documentation](https://www.nicehash.com/help/how-to-create-a-worker)

**Comment by fireice-uk** [comment]
That's correct. The only thing to be tested  is whether the users are still able to log in. We can't rewrite the poolside code obviously.

**Comment by psychocrypt** [comment]
Ok than I will merge this PR tomorrow. Please ignore the OSX build issue I
will fix it soon.

**Comment by Simaex** [comment]
I can confirm that for xmr-stak 2.3.0 nicehash worker name is correctly identified and user can log in only if using addres string in the form "YouBTCaddress.YouWorkerName". Setting "rig_ID" parameter is not working.

**Pull request merged**
