### PR TITLE
add Mesa OpenCL support

### PR DESCRIPTION
**Pull request by psychocrypt**
- allow usage of Mesa OpenCl

Select Mesa OpenCL only if there is no AMD OpenCl available

### CODE REVIEW

**Comment by rhlug** [comment]
It says you added Mesa support, but then elsewhere I read that OpenCL v1.1 is not supported?

I have latest everything installed here..
```
Number of platforms                               1
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 18.1.0-devel - padoka PPA
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   Clover
Number of devices                                 4
  Device Name                                     Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 7.0.0)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 Mesa 18.1.0-devel - padoka PPA
  Driver Version                                  18.1.0-devel - padoka PPA
  Device OpenCL C Version                         OpenCL C 1.1 
```

So are you saying it still wont work because OpenCL 1.1?

**Comment by psychocrypt** [comment]
sry OpenCL is really outdated and will not be suppoted.

**Comment by rhlug** [comment]
So is there any known working config for FOSS amdgpu + mesa + libclc?  I tried a couple different mesas with different llvms.   Everything compiles, the cards are detected, clinfo looks good, but xmr-stak core dumps.

```
[2018-03-26 15:09:54] : Mining coin: monero7
[2018-03-26 15:09:54] : Found AMD platform index id = 0, name = Mesa
[2018-03-26 15:09:54] : No AMD platform found select Mesa as OpenCL platform
[2018-03-26 15:09:54] : Found OpenCL GPU Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 7.0.0).
[2018-03-26 15:09:54] : Found OpenCL GPU Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 7.0.0).
[2018-03-26 15:09:54] : Found OpenCL GPU Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 7.0.0).
[2018-03-26 15:09:54] : Found OpenCL GPU Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 7.0.0).
[2018-03-26 15:09:54] : AMD: GPU configuration stored in file 'amd.txt'
[2018-03-26 15:09:54] : Compiling code and initializing GPUs. This will take a while...
[2018-03-26 15:09:54] : WARNING: using non AMD device: Mesa
[2018-03-26 15:09:54] : Device 0 work size 8 / 32.
Segmentation fault (core dumped)
```

```
[2018-03-26 16:36:21] : Mining coin: monero7
[2018-03-26 16:36:21] : Found AMD platform index id = 0, name = Mesa
[2018-03-26 16:36:21] : No AMD platform found select Mesa as OpenCL platform
[2018-03-26 16:36:21] : Found OpenCL GPU Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0).
[2018-03-26 16:36:21] : Found OpenCL GPU Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0).
[2018-03-26 16:36:21] : Found OpenCL GPU Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0).
[2018-03-26 16:36:21] : Found OpenCL GPU Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0).
[2018-03-26 16:36:21] : AMD: GPU configuration stored in file 'amd.txt'
[2018-03-26 16:36:21] : Compiling code and initializing GPUs. This will take a while...
[2018-03-26 16:36:21] : WARNING: using non AMD device: Mesa
[2018-03-26 16:36:21] : Device 0 work size 8 / 32.
Segmentation fault (core dumped)
```

**Comment by rhlug** [comment]
```
NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Clover
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [MESA]
  clCreateContext(NULL, ...) [default]            Success [MESA]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (4)
    Platform Name                                 Clover
    Device Name                                   Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0)
    Device Name                                   Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0)
    Device Name                                   Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0)
    Device Name                                   Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (4)
    Platform Name                                 Clover
    Device Name                                   Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0)
    Device Name                                   Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0)
    Device Name                                   Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0)
    Device Name                                   Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0)

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.8
  ICD loader Profile                              OpenCL 1.2
	NOTE:	your OpenCL library declares to support OpenCL 1.2,
		but it seems to support up to OpenCL 2.1 too.
```

**Comment by rhlug** [comment]
Also, I must say, I have my Vegas working on ethminer w/ Mesa OpenCL... so there is no reason why xmr-stak should not work.


```
# ./ethminer --list-devices

Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0)
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8568094720
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 5997666304
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[0] [1] Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0)
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8568094720
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 5997666304
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[0] [2] Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0)
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8568094720
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 5997666304
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[0] [3] Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0)
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8568094720
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 5997666304
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
```


```
 cl  19:26:16|cl-0    |  Platform: Clover
 cl  19:26:16|cl-0    |  Device:   Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-996-lowlatency, LLVM 6.0.0)  / OpenCL 1.1 Mesa 18.1.0-devel
 cl  19:26:16|cl-0    |  OpenCL 1.1  not supported, but platform Clover might work nevertheless. USE AT OWN RISK!
 cl  19:26:16|cl-0    |  OpenCL kernel: Stable kernel
 ...
  m  19:32:36|ethminer|  Speed  38.45 Mh/s    gpu/0 38.45  [A8+0:R0+0:F0] Time: 00:06
  ℹ  19:32:39|cl-0    |  Nonce 0x2fe8750a14b0d91e submitted to eth-us2.dwarfpool.com
  ℹ  19:32:40|stratum |  **Accepted  in 66 ms.
  m  19:32:41|ethminer|  Speed  38.47 Mh/s    gpu/0 38.47  [A9+0:R0+0:F0] Time: 00:06
  m  19:32:46|ethminer|  Speed  38.47 Mh/s    gpu/0 38.47  [A9+0:R0+0:F0] Time: 00:06
```

```
MINING eth
GPU #0
-----------------------------------------------------------------------------------------
  m  19:30:31|ethminer|  Speed  38.15 Mh/s    gpu/0 38.15  [A4+0:R0+0:F0] Time: 00:04
  m  19:30:36|ethminer|  Speed  38.07 Mh/s    gpu/0 38.07  [A4+0:R0+0:F0] Time: 00:04
-----------------------------------------------------------------------------------------
GPU #1
-----------------------------------------------------------------------------------------
  m  19:30:32|ethminer|  Speed  38.12 Mh/s    gpu/0 38.12  [A4+0:R0+0:F0] Time: 00:04
  m  19:30:37|ethminer|  Speed  38.20 Mh/s    gpu/0 38.20  [A4+0:R0+0:F0] Time: 00:04
-----------------------------------------------------------------------------------------
GPU #2
-----------------------------------------------------------------------------------------
  m  19:30:38|ethminer|  Speed  37.43 Mh/s    gpu/0 37.43  [A5+0:R0+0:F0] Time: 00:04
  m  19:30:43|ethminer|  Speed  37.49 Mh/s    gpu/0 37.49  [A5+0:R0+0:F0] Time: 00:04
-----------------------------------------------------------------------------------------
GPU #3
-----------------------------------------------------------------------------------------
  m  19:30:35|ethminer|  Speed  37.52 Mh/s    gpu/0 37.52  [A4+0:R0+0:F0] Time: 00:04
  m  19:30:40|ethminer|  Speed  37.47 Mh/s    gpu/0 37.47  [A4+0:R0+0:F0] Time: 00:04
-----------------------------------------------------------------------------------------
```

**Pull request merged**
