### PR TITLE
Rename "MacOS" to "macOS"

### PR DESCRIPTION
**Pull request by b-**
Apple has a silly way of capitalizing things, but it's still part of the name.

Basically this pull request is just `s/MacOS/macOS/g`

### CODE REVIEW

**Comment by Raginglikeaboss** [comment]
Good catch.  I agree it may seem silly if Apple but I believe this pull request show be quickly incorporated.  It helps the final product be more refined and polished.

**Comment by fireice-uk** [comment]
@b- Can you squash this pr to a single commit?

**Comment by b-** [comment]
I know this is a total newbie question I shouldn’t have to ask here, but how do I squash commits? I won’t have to undo everything and then redo it, will I? :/

**Comment by XhmikosR** [comment]
@fireice-uk: you can choose to squash when merging, https://github.com/blog/2141-squash-your-commits

**Comment by fireice-uk** [comment]
@XhmikosR 

Last time I tried to skirt around having merge commits I broke the whole repo :D. I wouldn't do it on a dev or stable. 

@b- 

Those commands (run them in the project dir) should do the trick

```
git reset --soft HEAD~6
git commit --amend
git push -f
```

The last one is destructive, so preferably verify that everything is ok before running it. You can use ```git log``` to view the new commit history.

**Comment by b-** [comment]
boom

**Comment by fireice-uk** [comment]
Note to self: CI fails here can be ignored.

**Pull request merged**
