### PR TITLE
Monero Cryptonight variants, and add one for v7

### PR DESCRIPTION
**Pull request by moneromooo**
Please make sure your PR is against **dev** branch. Merging PRs directly into master branch would interfere with our workflow.

### CODE REVIEW

**Comment by moneromooo** [comment]
See https://github.com/monero-project/monero-site/pull/599/files (not published yet)

**Comment by psychocrypt** [comment]
Thank you for providing the patch to support the upcoming POW change.
Never the less I will point to https://github.com/monero-project/monero/pull/3253#issue-168597884.

@moneromooo Is there a test net running with the new pow and is there a pool available?

**Comment by fireice-uk** [comment]
I will have a mock pool to test performance (**not correctness**) up tomorrow.

**Comment by fireice-uk** [comment]
With regards to merging, I'm against it as-is. When the core team actually settles on an algorithm we can decide.

**Comment by fireice-uk** [comment]
I will close this PR as the change looks half-cocked and doesn't match the algorithm under consideration now.

**Pull request closed without merging**
