### PR TITLE
Increase cache threads to 10

### PR DESCRIPTION
**Pull request by dancudds**
Please make sure your PR is against **dev** branch. Merging PRs directly into master branch would interfere with our workflow.
Useful for cache more than 10MB

### CODE REVIEW

**Comment by fireice-uk** [comment]
There is not enough registers in cpu to fit 6 or more interleaved hashes. You will actually make things slower by hitting the stack all the time.

**Comment by dancudds** [comment]
@fireice-uk is 5 the limit despite larger cache?

**Comment by fireice-uk** [comment]
Yes.

**Comment by dancudds** [comment]
I seem to make it a lot faster but some invalid shares

**Comment by fireice-uk** [comment]
Please post the cpuinfo, os, config and the result of `xmr-stak -V` and I will have a look.

**Comment by sfalpha** [comment]
I tried 6 and it's faster on some CPU. But still with invalid shares.
7 or more got no improvement or slower.

**Comment by simonlui** [comment]
@fireice-uk I'm confused. Unless you are strictly talking about x86, which has only 8 registers to use which would explain the limit, couldn't this be implemented on a conditional basis if the binary was compiled into a 64 bit binary because x86-64 has double the registers as x86 (16)?

**Comment by fireice-uk** [comment]
@simonlui Registers don't work the way you think they do. It takes much more than just a single number (a register) to make a calculation, let alone a thread. In this particular case we have 16 XMM registers and 16 general registers as x86 is unsupported.

Closing as @dancudds seems to have disappeared.

**Comment by dancudds** [comment]
Sorry I had left it so long - a lot of this was beyond me. @fireice-uk what do you need from me? Is it worth debugging this?

**Comment by simonlui** [comment]
@fireice-uk I'm still confused, are you saying that xmr-stak is already taking advantage of x86-64's 16 registers and that's still not enough to store more than 6 hashes without spilling over CPU cache?

**Comment by dancudds** [comment]
@simonlui do you have experience in 64 bit? I added code for up to 10 cache threads in my branch but I get invalid shares the more I increase it

**Pull request closed without merging**
