### PR TITLE
Affinity fix version B

### PR DESCRIPTION
**Pull request by fireice-uk**
Order of calls in this PR
1. thd_setaffinity, not in this thread
2. bindMemoryToNUMANode

### CODE REVIEW

**Comment by psychocrypt** [comment]
All three versions are working without any issues. I prefer version B, @fireice-uk what is your favorite patch?
The version B is easy to read and more intuitive than version C with the feature.

**Comment by psychocrypt** [comment]
Could you use the some mechanisms to set the affinity for the back-ends amd and nvidia

**Comment by fireice-uk** [comment]
@psychocrypt This one fails to set affinity on Windows too.

**Comment by psychocrypt** [comment]
Ahh I tested only linux :(

**Pull request merged**
