### PR TITLE
allow to diable UAC dialog

### PR DESCRIPTION
**Pull request by psychocrypt**
- remove CMake option `WIN_UAC`
- spawn UAC dialog via restarting xmr-miner with administrator right
- allow to disable UAC with `--noUAC`
- update documentation
- remove usage section with help message (output depends on OS)

### CODE REVIEW

**Comment by fireice-uk** [comment]
I should get some time to test it this Sunday.

**Comment by fireice-uk** [comment]
@psychocrypt This PR spawns infinite processes when launched on Win 7 with a double-click

**Comment by psychocrypt** [comment]
Arrggs I have currently no windows7. I think the option --noUAC is not
detected after the start of the process with high privilegs.
Could you debug it? Else I will do is in the next two days.

**Comment by fireice-uk** [comment]
Way too busy today. I just managed to test this and #313 , I will merge that one when this is fixed (my Nvidia system runs on Win7 while AMD on Linux).

**Comment by psychocrypt** [comment]
@fireice-uk I checked this code on two independent windows 7 systems and can not reproduce your infinite loop. Could you please test it with a clean code version again. 

[This](https://github.com/fireice-uk/xmr-stak/pull/305/files#diff-6c13e8fdffaf680d2e2876486b6124abR286) line should avoid that the miner starts in an infinite loop. If you still get this error could you please print `argv` in the first line of the main.

**Comment by psychocrypt** [comment]
ready to merge

**Comment by Simon0Harms** [comment]
> On Windows 10 it is only needed once to set up the account to use them.

Can you explain this?

**Comment by fireice-uk** [comment]
On Windows the user needs to have a special permission to use large pages. The miner will auto-magically do that if the user hasn't got them, but it needs to be ran as administrator.

**Pull request merged**
