### PR TITLE
adding qrl as a config option

### PR DESCRIPTION
**Pull request by jleni**
Adding QRL ( https://theqrl.org/ ) as a configuration option.

### CODE REVIEW

**Comment by jleni** [comment]
@psychocrypt @fireice-uk 
Any chance you could accept/merge this? QRL mainnet is about to be launching very soon. I am sure people will be happy to use xmr-stak.

**Comment by calvix** [comment]
+1

**Comment by happysmash27** [comment]
+1

**Comment by Wyc0** [comment]
+1

**Comment by psychocrypt** [comment]
If this coin pass 5MH/s please reopen this PR until than please use `cryptonight_v7`. We like to avoid that we have to much small coins in the portfolio. This  reduce the risk that the coin algorithm combination in xmr-stak is to fast outdated due to the new hoppy in the crypto world (change you algorithm^^)

**Comment by jleni** [comment]
Hi @psychocrypt 
QRL is over 5MH/s

You can check in some of the existing mining pools (just a couple of links as an example):
http://qrl.quantapool.com/
http://qrlmining.info/
https://qrl.herominers.com/

**Pull request closed without merging**
