### PR TITLE
Add support for CryptoNight Haven (small Heavy tweak)

### PR DESCRIPTION
**Pull request by havenprotocol**
Haven is hardforking in the next few weeks and making a small change to the algo in order to remove nicehash. The patch contains that tweak and allows the miner to autoswitch once we hit V3.

### CODE REVIEW

**Comment by psychocrypt** [comment]
please provide a test pool and a testnet wallet address

**Comment by havenprotocol** [comment]
http://159.203.102.63/

This is a testnet that switches to V3 (hardfork that contains the new algo) at block 20 so you can test the auto switch by selecting haven with the patch. This testnet is at block 12 currently.

Connect with 159.203.102.63:3333 in your miner and use address:
hvxy3PUxjTRN6fnb4vvsauU3aDbMqD2BRPKpkzBFzdKr8Hm5dKqLEJtd7FmRSKRk9KR9HaXWTVR1jc9eGzXdiDvN8cFKQBYFbo

**Comment by havenprotocol** [comment]
Just making some modifications the test pool to reflect new changes.

**Comment by psychocrypt** [comment]
I will update your PR after #1637 is merged. Because your algorithm id 8 will conflict with the other  PR. Do not worry I will fix it.
Do you tested the changes on all platforms cpu/nvidia/amd?

**Comment by havenprotocol** [comment]
Tested and confirmed working on all platforms.
Hardfork block when this switch is due to happen is set at 89200 which is:

2:15 PM 14th June 2018 (NZDT/GMT +12)
2:15 AM 14th June 2018  (GMT)
10:15 PM 13th June 2018 (New York/GMT -4)
7:15 PM 13th June 2018 (California/GMT -7)

**Comment by Florigs** [comment]
please update it we need it then on hiveos!

**Comment by psychocrypt** [comment]
@havenprotocol I pushed a change on top of you commit to simplify the rebase. Than I realized that I need to squash the changes to have an easy live during the rebase. I will close this PR and open a new rebased PR and will add you as author.

**Comment by psychocrypt** [comment]
replaced by #1652

**Comment by psychocrypt** [comment]
binaries are available in the newest release https://github.com/fireice-uk/xmr-stak/releases/tag/2.4.5

**Pull request closed without merging**
