### PR TITLE
Add a benchmark only option (--do-benchmark)

### PR DESCRIPTION
**Pull request by jimmielin**
In response to #1162 since it is fairly useful for offline tests. This simply adds a CLI option `--do-benchmark` and hooks it to the existing `do_benchmark()` code.

### CODE REVIEW

**Comment by psychocrypt** [comment]
Have you checked if this works with cpu,nvidia and amd gpus.

**Comment by jimmielin** [comment]
@psychocrypt I run CPUs only so unfortunately can't test the GPU aspect, sorry. Since it uses the existing `do_benchmark()` it should work I believe.

Would anyone be able to give this a test run please?

**Comment by fireice-uk** [comment]
This needs to be checked, as the primary reason why this is not in is that benchmark was an xmr-stak-cpu feature.

**Comment by ChaosMarc** [comment]
Works for me with CPU (i7-6700HQ) + Nvidia GeForce 940MX)  
```
$ ./xmr-stak.exe --do-benchmark
-------------------------------------------------------------------
xmr-stak 2.2.0 8152467

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-03-19 10:15:49] : Start mining: MONERO
!!!! Doing only a benchmark and exiting. To mine, remove the --do-benchmark option. !!!!
[2018-03-19 10:15:49] : Running a 60 second benchmark...
[2018-03-19 10:15:50] : Starting NVIDIA GPU thread 0, no affinity.
[2018-03-19 10:15:51] : Found AMD platform index id = 2, name = Advanced Micro Devices, Inc.
[2018-03-19 10:15:51] : WARNING: CL_DEVICE_NOT_FOUND when calling clGetDeviceIDs for of devices.
[2018-03-19 10:15:51] : WARNING: No AMD device found.
[2018-03-19 10:15:51] : WARNING: backend AMD disabled.
[2018-03-19 10:15:51] : Starting 1x thread, affinity: 2.
[2018-03-19 10:15:51] : hwloc: memory pinned
[2018-03-19 10:15:51] : Starting 1x thread, affinity: 4.
[2018-03-19 10:15:51] : hwloc: memory pinned
[2018-03-19 10:15:51] : Starting 1x thread, affinity: 6.
[2018-03-19 10:15:51] : hwloc: memory pinned
[2018-03-19 10:16:51] : Thread 0: 78.3 H/S
[2018-03-19 10:16:51] : Thread 1: 43.7 H/S
[2018-03-19 10:16:51] : Thread 2: 43.6 H/S
[2018-03-19 10:16:51] : Thread 3: 42.4 H/S
[2018-03-19 10:16:51] : Total: 208.0 H/S
```

**Comment by psychocrypt** [comment]
I checked this PR and it looks like all backends will be used.

**Comment by psychocrypt** [comment]
thy for you PR, I added the benchmark option into the last release.

**Pull request closed without merging**
