### PR TITLE
Fix cases where positive feedback was still occurring.

### PR DESCRIPTION
**Pull request by fireice-uk**
Fix for #123

### CODE REVIEW

**Comment by fireice-uk** [comment]
@psychocrypt Let me know when the fix is tested and I will merge it on the console.

**Comment by psychocrypt** [comment]
I can only review te code I don't know what I should test. I assume that
you tested it already.

**Comment by psychocrypt** [comment]
Could you please rebase this PR

**Comment by fireice-uk** [comment]
All done. See point 3 from #123

**Comment by psychocrypt** [comment]
#123 has no point 3

**Pull request merged**
