### PR TITLE
AMD APP SDK 3.0 url fix

### PR DESCRIPTION
**Pull request by tworec**
dropbox link is broken

Please make sure your PR is against **dev** branch. Merging PRs directly into master branch would interfere with our workflow.

### CODE REVIEW

**Comment by JokerGermany** [comment]
Duplicate
https://github.com/fireice-uk/xmr-stak/pull/1787

**Comment by tworec** [comment]
#1787 is for windows, and this is for Linux...

**Comment by psychocrypt** [comment]
thx for the PR but please open pull requests always against the dev branch. As @JokerGermany  wrote the invalid link is already fixed and will go to the master (stable) branch with the next release.

**Comment by psychocrypt** [comment]
@tworec could you please reopen this PR against the dev branch

**Comment by Spudz76** [comment]
My personal mirrors, no thanks for being put into docs, thanks.

If they end up in docs, I will drop the files immediately.

**Comment by Spudz76** [comment]
Linux: [AMD-APP-SDKInstaller-v3.0.130.136-GA-linux64.tar.bz2](https://www.yourupload.com/view/1824158)
Windows: [AMD-APP-SDKInstaller-v3.0.130.135-GA-windows-F-x64.exe](https://www.yourupload.com/view/1824157)

These are approved and can be in the docs, at least it spools a few ads, versus ripping off my bandwidth.

**Comment by Spudz76** [comment]
I've set my original links to 301 redirect to better location, thus fixing my personal problem no matter what people try to do (or how many sites its been C&P'd to...).

**Pull request closed without merging**
