### PR TITLE
CPU ONLY Docker alpine build

### PR DESCRIPTION
**Pull request by rowanruseler**
Created an alpine build for CPU only farming, always good to support xmr
with some cpu compute of available or lingering devices.

Please see README.md for more information

### CODE REVIEW

**Comment by lucaforni** [comment]
Hi,
I tried to run your docker but when i have this error where the container start:
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"./run.sh\": permission denied".

Docker version 17.09.0-ce, build afdb6d4 on OSX 10.13.1
Any idea?
Thank you

**Comment by rowanruseler** [comment]
@lucaforni I decided not to grand execute rights (chmod +x) in the Dockerfile, but instead just to grand it in the repo myself.

Can you attempt to give it execute rights and try again?

**Comment by lucaforni** [comment]
Ok,
It works
Thank you

**Comment by rowanruseler** [comment]
@lucaforni just added it to the Dockerfile, nice catch. It should be easier for people to run if it is just another layer within the Dockerfile.

If you have any other issues, let me know! Cheers.

**Comment by lucaforni** [comment]
There is a type in setup.sh:
POOL_ADDRESS=${POOL_ADDRESS:-pool.supportxmr.com:3333}

**Comment by psychocrypt** [comment]
Thank you for your pull request. 
 
I am not sure if the way how you created the config file is a good way. The problem is that we need to check you scripts each time we add now options to the config file e.g. #315 and #313.
I think it is not possible for use to maintain the scripts.

Is it possible that you create a own repository with your extensions. We can later on link it somewhere in the documentation (in a section with useful extensions). I think a own project with xmr-stak as submodule would be good. This will give you the possibility to point to a exact version and a update from our side will not break the scripts.

**Comment by rowanruseler** [comment]
@psychocrypt I would love to maintain it, so I did as adviced: https://github.com/rowanruseler/xmr-stak-cpu-alpine

Let me know if you want some addional credits or anything else in it, cheers.

**Comment by krll-k** [comment]
@rowanruseler can I skip the video cards through the docker?

**Comment by rowanruseler** [comment]
@krll-k 'skip' as in "not use them" or 'skip' as in "run them through docker" ?

**Pull request closed without merging**
