### PR TITLE
On-demand elevation

### PR DESCRIPTION
**Pull request by fireice-uk**

### CODE REVIEW

**Comment by psychocrypt** [comment]
Do I need to test this PR on my setup or is it already well tested?

**Comment by fireice-uk** [comment]
I tested it on Windows 7, Windows 10 is needed .... Actually this reminds me that I forgot to add compatibility manifest to appease the vengeful Microsoft gods with a sacrifice of virgin blood...

I will change it to WIP status

**Comment by psychocrypt** [comment]
If it is ready to test I can test it on win10.

**Comment by fireice-uk** [comment]
@psychocrypt It is ready for testing now. I had to include a full-blown manifest and change the code to _the way Microsoft wants it to be done_ ...

**Comment by psychocrypt** [comment]
tested by @fireice-uk  and @JerichoJones

**Comment by JerichoJones** [comment]
Tested OK. Nice Job!

----------------------
----------------------
1st run (UAC prompt)
----------------------
----------------------
2017-12-26 17:01:33] : Elevating because we need to set up fast memory privileges.
[2017-12-26 17:01:33] : MEMORY INIT ERROR: Added SeLockMemoryPrivilege to the current account. You need to reboot for it to work
[2017-12-26 17:01:33] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
[2017-12-26 17:01:33] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
[2017-12-26 17:01:33] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
[2017-12-26 17:01:33] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
[2017-12-26 17:01:33] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
-------------------------------------------------------------------
xmr-stak 2.2.0 b216f39a

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-26 17:01:34] : Start mining: MONERO
[2017-12-26 17:01:35] : Starting NVIDIA GPU thread 0, no affinity.
[2017-12-26 17:01:35] : MEMORY ALLOC FAILED: VirtualAlloc failed.
[2017-12-26 17:01:35] : Compiling code and initializing GPUs. This will take a while...
[2017-12-26 17:01:36] : Device 0 work size 8 / 32.
[2017-12-26 17:01:41] : Device 0 work size 8 / 32.
[2017-12-26 17:01:46] : Starting AMD GPU thread 0, affinity: 13.
[2017-12-26 17:01:46] : hwloc: memory pinned
[2017-12-26 17:01:46] : Starting AMD GPU thread 1, affinity: 15.
[2017-12-26 17:01:46] : MEMORY ALLOC FAILED: VirtualAlloc failed.
[2017-12-26 17:01:46] : hwloc: memory pinned
[2017-12-26 17:01:46] : MEMORY ALLOC FAILED: VirtualAlloc failed.
[2017-12-26 17:01:46] : Starting 1x thread, affinity: 0.
[2017-12-26 17:01:46] : hwloc: memory pinned
[2017-12-26 17:01:46] : Starting 1x thread, affinity: 2.
[2017-12-26 17:01:46] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
[2017-12-26 17:01:46] : hwloc: memory pinned
[2017-12-26 17:01:46] : Starting 1x thread, affinity: 4.
[2017-12-26 17:01:46] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
[2017-12-26 17:01:46] : hwloc: memory pinned
[2017-12-26 17:01:46] : Starting 1x thread, affinity: 6.
[2017-12-26 17:01:46] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
[2017-12-26 17:01:46] : hwloc: memory pinned
[2017-12-26 17:01:46] : Starting 1x thread, affinity: 8.
[2017-12-26 17:01:46] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
[2017-12-26 17:01:46] : hwloc: memory pinned
[2017-12-26 17:01:46] : Starting 1x thread, affinity: 10.
[2017-12-26 17:01:46] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
[2017-12-26 17:01:46] : hwloc: memory pinned
[2017-12-26 17:01:46] : Starting 1x thread, affinity: 12.
[2017-12-26 17:01:46] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
[2017-12-26 17:01:46] : hwloc: memory pinned
[2017-12-26 17:01:46] : Starting 1x thread, affinity: 14.
[2017-12-26 17:01:46] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
[2017-12-26 17:01:46] : hwloc: memory pinned
[2017-12-26 17:01:46] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
[2017-12-26 17:01:46] : Fast-connecting to pool.supportxmr.com:7777 pool ...
[2017-12-26 17:01:46] : Pool pool.supportxmr.com:7777 connected. Logging in...
[2017-12-26 17:01:47] : Difficulty changed. Now: 25000.
[2017-12-26 17:01:47] : Pool logged in.
[2017-12-26 17:01:55] : Difficulty changed. Now: 25000.
[2017-12-26 17:01:55] : New block detected.

----------------------
----------------------
2nd run (After reboot, No UAC prompt)
----------------------
----------------------
C:\XMR-STAK-3DBoxx\xmr-stak-topic-on-demand-elevation>xmr-stak.exe
-------------------------------------------------------------------
xmr-stak 2.2.0 b216f39a

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-26 17:04:30] : Start mining: MONERO
[2017-12-26 17:04:32] : Starting NVIDIA GPU thread 0, no affinity.
[2017-12-26 17:04:32] : Compiling code and initializing GPUs. This will take a while...
[2017-12-26 17:04:37] : Device 0 work size 8 / 32.
[2017-12-26 17:04:46] : Device 0 work size 8 / 32.
[2017-12-26 17:04:51] : Starting AMD GPU thread 0, affinity: 13.
[2017-12-26 17:04:51] : hwloc: memory pinned
[2017-12-26 17:04:51] : Starting AMD GPU thread 1, affinity: 15.
[2017-12-26 17:04:51] : hwloc: memory pinned
[2017-12-26 17:04:51] : Starting 1x thread, affinity: 0.
[2017-12-26 17:04:51] : hwloc: memory pinned
[2017-12-26 17:04:51] : Starting 1x thread, affinity: 2.
[2017-12-26 17:04:51] : hwloc: memory pinned
[2017-12-26 17:04:51] : Starting 1x thread, affinity: 4.
[2017-12-26 17:04:51] : hwloc: memory pinned
[2017-12-26 17:04:51] : Starting 1x thread, affinity: 6.
[2017-12-26 17:04:51] : hwloc: memory pinned
[2017-12-26 17:04:51] : Starting 1x thread, affinity: 8.
[2017-12-26 17:04:51] : hwloc: memory pinned
[2017-12-26 17:04:51] : Starting 1x thread, affinity: 10.
[2017-12-26 17:04:51] : hwloc: memory pinned
[2017-12-26 17:04:51] : Starting 1x thread, affinity: 12.
[2017-12-26 17:04:51] : hwloc: memory pinned
[2017-12-26 17:04:51] : Starting 1x thread, affinity: 14.
[2017-12-26 17:04:51] : hwloc: memory pinned
[2017-12-26 17:04:51] : Fast-connecting to pool.supportxmr.com:7777 pool ...
[2017-12-26 17:04:51] : Pool pool.supportxmr.com:7777 connected. Logging in...
[2017-12-26 17:04:51] : Difficulty changed. Now: 25000.
[2017-12-26 17:04:51] : Pool logged in.

**Pull request merged**
