### PR TITLE
Add new Algorithm for cryptonight_armor

### PR DESCRIPTION
**Pull request by 2acoin**
Add new algorithm for cryptonight_armor
 * Add new currency for 2ACoin

### CODE REVIEW

**Comment by fireice-uk** [comment]
Sorry but I can't see any difference between your algo and cn_turtle

**Comment by psychocrypt** [comment]
Please use `cryptonight_turtle` to mine your coin. The coin should have at least 8MH/s global hashrate before we will add it.

**Comment by psychocrypt** [comment]
cn_turtle is 4 times faster than e.g. Monero. The network hash of the
suggeated coin is currently 200kh/s this coresponse to 50kh/s monero
hashrate. Since it is possible still possible to mine even if the coin is
not supported nativly there is no need to support it.

**Comment by timetoseek** [comment]
> Please use `cryptonight_turtle` to mine your coin. The coin should have at least 8MH/s global hashrate before we will add it.

Thank you, I was curious at which point you might support some of the new ones...  so a newish coin like GRIN (at only ~2MH/s), is nowhere on the horizon :frowning:

**Comment by Spudz76** [comment]
Newish coins should send their programmers over here, probably well before their dumb coin launches, and add their dumb coin to the code themselves (via PR) to support their coin, if they wanted it supported at launch because nobody else is going to do it for them until the coin is popular.

This is how Open Source works?  It is not there to do all your work for you upon request.  Also stealing code technically, by not submitting the changes upstream.

Most new coins fork a miner, terribly hack the code like they don't know what they are doing, and then launch off of that and never properly clean up their hacks and submit an acceptable PR.  It's not really that hard to match a projects code style rules, and "do it right", before submitting a patch.  We also won't clean up terrible code, it can be lightly messy, but not completely nasty laughable hacks.  Most forked new-coin hacks don't actually add a new algo (properly) but destroy an existing one (thus the code can't be upstreamed) and probably other problems I can't recall right now.

When a coin is some silly minor change like number of rounds or whatever (CN-half, CN-double) then those are easier to add.  When they have some new tweak other than that, it is much more difficult.

Anyway that's why new coins get no love from here (and probably all other mainstream miner apps).  Otherwise we'd all be adding abandonware-coins constantly while most of them die off.  Whoever starts a coin should be the only one to lose a bunch of time supporting *their* coin.

**Comment by timetoseek** [comment]
> Newish coins should send their programmers over here, probably well before their dumb coin launches, and add their dumb coin to the code themselves (via PR) to support their coin, if they wanted it supported at launch because nobody else is going to do it for them until the coin is popular.
> 
> This is how Open Source works? It is not there to do all your work for you upon request. Also stealing code technically, by not submitting the changes upstream.
> 
> Most new coins fork a miner, terribly hack the code like they don't know what they are doing, and then launch off of that and never properly clean up their hacks and submit an acceptable PR. It's not really that hard to match a projects code style rules, and "do it right", before submitting a patch. We also won't clean up terrible code, it can be lightly messy, but not completely nasty laughable hacks. Most forked new-coin hacks don't actually add a new algo (properly) but destroy an existing one (thus the code can't be upstreamed) and probably other problems I can't recall right now.
> 
> When a coin is some silly minor change like number of rounds or whatever (CN-half, CN-double) then those are easier to add. When they have some new tweak other than that, it is much more difficult.
> 
> Anyway that's why new coins get no love from here (and probably all other mainstream miner apps). Otherwise we'd all be adding abandonware-coins constantly while most of them die off. Whoever starts a coin should be the only one to lose a bunch of time supporting _their_ coin.

I agree :100:%, and thank you for such a succinct overview (and XMR-Stak is awesome!!) :clap:

**Pull request closed without merging**
