### PR TITLE
Something minor

### PR DESCRIPTION
**Pull request by taisel**
Probably needs to be vetted because tired me did this, but I was trying to explore the code and tried merging some buffers.

### CODE REVIEW

**Comment by taisel** [comment]
Also did this when y'all updated the code, so there might be something amiss now. Again, tired me explorin' the code.

**Comment by taisel** [comment]
https://github.com/fireice-uk/xmr-stak/commit/efc8dc447adc8fcbf2c1faf0de2dacf8d38889ac#diff-5b1d0c2b2acc529d2838a0b2eb26b3c9

Yeah, we've got two different recent passes on the same file fightin'.

**Comment by taisel** [comment]
I just prefer using a multidimensional array over fancy pointer arith, as the hardcoded array offsets can be often baked into the machine code directly, rather than reside in data.

**Comment by taisel** [comment]
I can see what y'all did to optimize as well. Re-ordering the XOR sequencies to make the AES local buffer reads more sequential.

**Comment by psychocrypt** [comment]
Thanks for you PR. Pleas reopen the PR against the `dev` branch. https://github.com/fireice-uk/xmr-stak/blob/master/CONTRIBUTING.md

Is this change giving use any hasr rate increase or is this only a style change?

**Pull request closed without merging**
