### PR TITLE
Proofreading

### PR DESCRIPTION
**Pull request by Spudz76**
Merged correctly this time with dev
Spelling repairs and some end of line whitespace chopping

### CODE REVIEW

**Comment by fireice-uk** [comment]
Thanks! This pr needs a squash and a rebase before it can be merged, can you perform that? If not I can give you some help.

**Comment by Spudz76** [comment]
I think that's a squash-rebase (merge/resolve/push)

**Comment by fireice-uk** [comment]
No, firstly you need to replay the commits on top of the dev to resolve the conflicts (rebase on to dev), this is different from merging.

Then you need to soft reset to make the commits go away (**not** the changes,  note **soft** reset), and commit the changes as a single commit.

**Comment by Spudz76** [comment]
eww I'll just refork and reapply in that case
sounds complicated
Probably screwed up my other two PR also?

**Comment by fireice-uk** [comment]
Yes, I don't like to have merge commits in PRs. If you want a more newbie friendly git interface try gitkraken - I use the Pro version myself.

**Comment by Spudz76** [comment]
Oh, I get it now.  You just want me to trounce my own follow up commits into one simple commit so your git-log is less of a compost heap.

Well if you didn't take so long to merge my PR I wouldn't have found more to add... :100:  haha

**Pull request closed without merging**
