### PR TITLE
cryptonight_v8 version 2

### PR DESCRIPTION
**Pull request by psychocrypt**
This PR adds the final changes for the upcoming cryptonight_v8 to the CPU and OpenCl backend.
It is currently not allowed to mine cryptonight_v8 with the CUDA backend. The CUDA backend is currently not updated.

Performance can be reported in https://github.com/fireice-uk/xmr-stak/issues/1851.
Please report here only code suggestions or bugs.

- for CUDA the changes from #1831 are reverted and a new schema with two threads per hash is introduced
- add ams for double hash (intel)

# todo
- [x] add native CUDA version
- [x] test double hash asm under WINDOWS

### CODE REVIEW

**Comment by SChernykh** [comment]
@psychocrypt Don't leave out double hash asm optimized version. The same version can be used both for Intel and AMD, and it's much faster than C++ code on both platforms.

**Comment by kio3i0j9024vkoenio** [comment]
Bug: Ubuntu 16.04 Compile fails on OpenCL:

Using current source from Test final Monero POW cryptonight_v8 #1851

miner@DL580-G7-6:~/xmr-stak-v8b/build$ cmake ..
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
-- Configuring done
-- Generating done
-- Build files have been written to: /home/miner/xmr-stak-v8b/build
miner@DL580-G7-6:~/xmr-stak-v8b/build$ make install
[  5%] Built target xmr-stak-asm
[ 21%] Built target xmr-stak-c
[ 70%] Built target xmr-stak-backend
[ 72%] Linking CXX shared library bin/libxmrstak_cuda_backend.so
[ 83%] Built target xmrstak_cuda_backend
[ 89%] Built target xmr-stak
make[2]: *** No rule to make target '/opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so', needed by 'bin/libxmrstak_opencl_backend.so'.  Stop.
CMakeFiles/Makefile2:259: recipe for target 'CMakeFiles/xmrstak_opencl_backend.dir/all' failed
make[1]: *** [CMakeFiles/xmrstak_opencl_backend.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Spudz76** [comment]
@kio3i0j9024vkoenio Try with either envvar `OpenCL_ROOT=/usr/local/cuda/targets/x86_64-linux` set, or if that doesn't help then full force with `-DOpenCL_INCLUDE_DIR=/usr/local/cuda/targets/x86_64-linux/include -DOpenCL_LIBRARY=/usr/local/cuda/targets/x86_64-linux/lib/libOpenCL.so.1.0.0` added to your cmake command

Or whatever `sudo updatedb` and then `locate include/CL` and `locate libOpenCL.so` give.  Avoid system `/usr/include/CL` and whatever is in `/usr/lib/` those are usually Mesa/Clover unless you've purged them on purpose.  Add-on drivers usually don't replace existing OpenCL implementations include/libs, rather just put their ICD pointer into `/etc/OpenCL/vendors/`

By default install, `/usr/local/cuda` is linked to whichever is the active CUDA SDK, while `locate` will not show links - so I've replaced my `locate` output of `/usr/local/cuda-9.1/blahblah` to just `/cuda/` then it will follow whichever is active in case of upgrade.

You still need the CUDA SDK (`cuda-*-dev` packages generally) as far as I know, but not the AMD APP SDK.  However when nothing is found it attempts to force APP SDK which is where it fails (non existent as it is probably not installed).

**Comment by kio3i0j9024vkoenio** [comment]
cmake .. -DOpenCL_INCLUDE_DIR=/usr/local/cuda/targets/x86_64-linux/include -DOpenCL_LIBRARY=/usr/local/cuda/targets/x86_64-linux/lib/libOpenCL.so.1.0.0

Fixed the problem.

Thanks

**Comment by kio3i0j9024vkoenio** [comment]
> @psychocrypt Don't leave out double hash asm optimized version. The same version can be used both for Intel and AMD, and it's much faster than C++ code on both platforms.

I second this request. I am only getting:

cryptonight_v8: 1293 H/s using XMR-Stak 1850/1851 latest version

whereas I am getting 1525 H/s using SChernykh XMR-Stak-CPU latest code with all the same v8 changes and the optimized asm for 1x and 2x threads.

**Comment by Spudz76** [comment]
@kio3i0j9024vkoenio The "double hash asm" is only for CPUs, it won't help your OpenCL hashrates at all.

**Comment by kio3i0j9024vkoenio** [comment]
> 
> 
> @kio3i0j9024vkoenio The "double hash asm" is only for CPUs, it won't help your OpenCL hashrates at all.

Yes I know that.

**Comment by psychocrypt** [comment]
update: I am still implementing the native NVIDIA backend. Everything takes longer than expected. The reason is that I found maybe a bug in the NVIDIA compiler nvcc.

**Comment by kio3i0j9024vkoenio** [comment]
Has the optimized double hash asm for CPU been added?

**Comment by psychocrypt** [comment]
Corrently not. But do not worry I will do it soon.

**Comment by SChernykh** [comment]
@psychocrypt Is NVIDIA backend issue something I can help with?

**Comment by psychocrypt** [comment]
Currently not. I workarounded the bug by adding a sync in between to avoid
a memory optimization which is wrong. I need now to clean the code before I
can push it. After tha I can have a deeper look into the performance. All
at all the biggest issue is the high register usage compared to v7.

**Comment by SChernykh** [comment]
Is it faster than current OpenCL version? If not, maybe it's better to port OpenCL instead?

**Comment by kio3i0j9024vkoenio** [comment]
> 
> 
> Is it faster than current OpenCL version? If not, maybe it's better to port OpenCL instead?

I certainly hope that the CUDA version will be faster than the OpenCL version as the OpenCL V8 version is terrible running on Nvidia GTX 750/750 Ti's as V8 performance is only 73.4 of what V7 produces.

https://github.com/fireice-uk/xmr-stak/issues/1851#issuecomment-424391311

**Comment by psychocrypt** [comment]
@SChernykh Bad new I can not push the CUDA code today. I have now invalid results on my  GTX1080, think I know where it is coming from but I need to test (this take some time) if I am right.

**Comment by Bathmat** [comment]
Issue building:
```
"C:\xmr-stak\xmr-stak-topic-cn8Version2\build-cuda\install.vcxproj" (default target) (1) ->
"C:\xmr-stak\xmr-stak-topic-cn8Version2\build-cuda\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\xmr-stak\xmr-stak-topic-cn8Version2\build-cuda\xmrstak_cuda_backend.vcxproj" (default target) (8) ->
(CustomBuild target) ->
  C:/xmr-stak/xmr-stak-topic-cn8Version2/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(213): error : identifier "uint"
is undefined [C:\xmr-stak\xmr-stak-topic-cn8Version2\build-cuda\xmrstak_cuda_backend.vcxproj]
  C:/xmr-stak/xmr-stak-topic-cn8Version2/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(213): error : identifier "uint"
is undefined [C:\xmr-stak\xmr-stak-topic-cn8Version2\build-cuda\xmrstak_cuda_backend.vcxproj]
```

**Comment by plavirudar** [comment]
> 
> 
> Issue building:
> 
> ```
> "C:\xmr-stak\xmr-stak-topic-cn8Version2\build-cuda\install.vcxproj" (default target) (1) ->
> "C:\xmr-stak\xmr-stak-topic-cn8Version2\build-cuda\ALL_BUILD.vcxproj" (default target) (3) ->
> "C:\xmr-stak\xmr-stak-topic-cn8Version2\build-cuda\xmrstak_cuda_backend.vcxproj" (default target) (8) ->
> (CustomBuild target) ->
>   C:/xmr-stak/xmr-stak-topic-cn8Version2/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(213): error : identifier "uint"
> is undefined [C:\xmr-stak\xmr-stak-topic-cn8Version2\build-cuda\xmrstak_cuda_backend.vcxproj]
>   C:/xmr-stak/xmr-stak-topic-cn8Version2/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(213): error : identifier "uint"
> is undefined [C:\xmr-stak\xmr-stak-topic-cn8Version2\build-cuda\xmrstak_cuda_backend.vcxproj]
> ```
> 
> EDIT: FYI, using CUDA9.2. Should I revert to 9.1?

Getting same error, where in the code do you specify the CUDA version?

**Comment by plavirudar** [comment]
@Bathmat Line 213 on `cude_core.cu` doesn't compile when `uint` is used on certain compile platforms (Windows?), changing it to `unsigned int` compiles as per https://github.com/nitishsrivastava/deepnet/issues/57

**Comment by Bathmat** [comment]
> @Bathmat Line 213 on `cude_core.cu` doesn't compile when `uint` is used on certain compile platforms (Windows?), changing it to `unsigned int` compiles as per [nitishsrivastava/deepnet#57](https://github.com/nitishsrivastava/deepnet/issues/57)

Cool, that fixed it. Thanks @plavirudar. Yes, compiling on Win10 v1803. Will test and publish results a little later (hopefully tonight).

**Comment by Blitss** [comment]
@psychocrypt cool, but still doing worse comparing to cn/8 (my previous tests: https://github.com/fireice-uk/xmr-stak/issues/1832#issuecomment-423481518) and bit better than OpenCL kernel.

```
PS C:\Users\Andrey\Documents\xmr-stak-cn8\xmr-stak\build\bin\Release> ./xmr-stak --currency cryptonight_v8  --benchmark
8 --benchwait  20 --benchwork 30 --noCPU --noAMD
-------------------------------------------------------------------
xmr-stak 2.4.7 010cbd9

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-10-01 20:50:32] : Mining coin: cryptonight_v8
!!!! Doing only a benchmark and exiting. To mine, remove the '--benchmark' option. !!!!
[2018-10-01 20:50:32] : Prepare benchmark for block version 8
[2018-10-01 20:50:32] : Starting NVIDIA GPU thread 0, no affinity.
CUDA [10.0/10.0] GPU#0, device architecture 61: "GeForce GTX 1060 6GB"... device init succeeded
[2018-10-01 20:50:32] : Wait 20 sec until all backends are initialized
[2018-10-01 20:50:52] : Start a 30 second benchmark...
[2018-10-01 20:51:22] : Benchmark Thread 0 nvidia: 393.5 H/S
[2018-10-01 20:51:22] : Benchmark Total: 393.5 H/S
```

**Comment by Bathmat** [comment]
@Blitss here are my tests with my GTX-1060. CNv8 is slower than v7 by design, but nvidia does appear to have a bigger drop in hashrate compared to CPU or AMD.
[CUDA test 1](https://github.com/fireice-uk/xmr-stak/issues/1851#issuecomment-425781831)
[CUDA test 2](https://github.com/fireice-uk/xmr-stak/issues/1851#issuecomment-425983819)

**Comment by Blitss** [comment]
@Bathmat well, i was trying to adjust threads but it didn't work for me. Setting threads for 30 made it 380H/s.

**Comment by Blitss** [comment]
@Bathmat are you overclocked card? Are you using Cuda 9 or 10 during build? I have exactly same card but not same results.
I used same config and got only 408.8H/s
image

**Comment by Bathmat** [comment]
@Blitss yes overclocked. +150 core, +500 mem = 2000 core, 4300 mem
I compiled with CUDA 9.2 and am using 397.64 driver

**Comment by Blitss** [comment]
@Bathmat I got a bit better results with same overclock - 461.5H/s against 508H/s on cn/7. About 10% lower.
I'm using CUDA 10 and 411.63 drivers.

I gonna check it on OS X later.

**Comment by psychocrypt** [comment]
@plavirudar I fixed the `uint` issue. It should now build without any issues under windows.

**Comment by Spudz76** [comment]
@Bathmat Don't forget the Pascal/10xx P2-lock and be sure to disable it ([this tool](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW))

I have used some 1060 6GB dual-fan full length PNY and they have P0 and P2 clocked identical so it doesn't matter - Blitss may have a card with "good" bios such as that
I also have used some 1060 6GB single-fan short layout MSI and they have a really garbage P2 clocking so unless I unlock, they run like they are half on power management (memory severely underclocked "for accuracy").

Since nvidia clocking is by offset, even if you "have the same clocking" your base clock may still be lower and thus the real effective clock will not be the same as someone else due different bios (base clocks).

Check with nvidia-smi while miner is running, start->run->cmd  then cd to the nvidia program files (I forget if they are in x86 or not) whichever has NVSMI folder, go in there.  Then you can run `nvidia-smi -q` while the miner is running to see what mode and actual clocks it is running (among tons of other info).

**Comment by psychocrypt** [comment]
I added the intel double hash ASM version from @SChernykh . (currently not tested under windows, feedback is welcome)

**Comment by Bathmat** [comment]
@Spudz76 Looks like the P2 vs P0 on my GTX-1060 isn't that drastic (200 Mhz on the mem clock). I set it to P0 and did the same +150 core/+500 mem and got 2000 core/4500 mem. This gave +20 h/s on both CNv7 and CNv8 (520 to 540 for CNv7, 460 to 480 for CNv8), so only about a 4% boost. Hopefully the extra 200 Mhz won't cause stability issues, but I doubt it. Thanks.

**Comment by Spudz76** [comment]
@Bathmat I had similar "fuzzy edge" on Hynix memory (also the MSI) whereas I can go like +500 over  those on the Samsung (PNY)

**Comment by Bathmat** [comment]
> @Bathmat I had similar "fuzzy edge" on Hynix memory (also the MSI) whereas I can go like +500 over those on the Samsung (PNY)

Gotta love Samsung memory... although, my Samsung AMD GPUs are taking the biggest hit with CNv8. But really, CNv8 levels the playing field for all mem brands.

**Comment by Spudz76** [comment]
Yeah I keep remembering, all ships sink the same with this fork, so the rate difference is somewhat negated anyway (other than mixing up which cards are "best" hash per watt a little bit, I guess)

**Comment by Spudz76** [comment]
> just in time compilation where cfg values are translated into defines
[NVRTC](https://docs.nvidia.com/cuda/nvrtc/index.html) does exactly what AMD OpenCL runtime compiler does, and is just nvcc wrapped in the driver runtime.

**Comment by srwx666** [comment]
Version: xmr-stak 2.4.7 a6ecf8d

on config with:
monero7 -> hashes OK
monero8 -> error : Cryptonight hash self-test failed. This might be caused by bad compiler optimizations.


sometimes segfault
Oct  5 13:24:19 localhost kernel: in xmr-stak[400000+15b000]
Oct  5 13:26:22 localhost kernel: xmr-stak[46693]: segfault at 0 ip 000000000043d4a8 sp 00007f409fffeb50 error 6
Oct  5 13:26:22 localhost kernel: xmr-stak[46692]: segfault at 0 ip 000000000043d4a8 sp 00007f40a4906b50 error 6 in xmr-stak[400000+15b000]

compiled as older versions with 
gcc version 7.1.1 20170526 (Red Hat 7.1.1-2) (GCC)

regards
A

**Comment by srwx666** [comment]
compiling the same code with:

gcc version 6.3.1 20170216 (Red Hat 6.3.1-3) (GCC)

both v8 and v7 are hashing OK

**Pull request merged**
